# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-testing:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install
        run: npm ci

      - name: Tests
        run: npm run test
        
      - name: Install allure
        run: npm install -g allure-commandline --save-dev
        
     # - name: Create Report
      - name: Allure Report with history
        uses: simple-elf/allure-report-action@v1.6

      #  if: always()
       # run: npm run report:generate
      #- uses: actions/upload-artifact@v1
       # if: always()
        #with:
         #  name: allure-report
          # path: ./allure-report
      
        
        
        
        
        
        
        
        
